name: maven

on:
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file kitchencloud/pom.xml

  check-build:

    runs-on: ubuntu-latest

    needs: build
    steps:
    - name: Check Build Status
      run: |
        if [ ${{ job.status }} == "success" ]; then
          echo "Build passed successfully."
          exit 0
        else
          echo "Build failed. PR cannot be merged."
          exit 1
        fi

