name: CARCARA | CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file kitchencloud/pom.xml

  check-build:

    runs-on: ubuntu-latest

    needs: build
    steps:
    - name: Check Build Status
      id: check_build
      run: |
        if [ ${{ job.status }} == "success" ]; then
          echo "Build passed successfully."
          echo "::set-output name=status::success"
        else
          echo "Build failed. PR cannot be merged."
          echo "::set-output name=status::failure"
        fi

    - name: Send Email Notification
      if: ${{ needs.build.result == 'success' }}
      uses: softprops/action-email@v2
      with:
        to: 'recipient@example.com' # Substitua pelo endereço de e-mail desejado
        from: 'igoructechnology@gmail.com'
        host: 'smtp.gmail.com'
        port: 587
        username: 'igoructechnology@gmail.com'
        password: ${{ secrets.EMAIL_PASSWORD }} # Melhor armazenar a senha como um segredo

  # ...outros jobs e steps podem continuar aqui
